### ISSUE TITLE
Can I use this with RealmSwift?

### ISSUE THREAD

**Issue by retsohuang** [bigfish24/ABFRealmMapView#1]

**Comment by bigfish24** [comment]
No it works with Swift bridging but not Realm Swift. I plan to add support though.

**Comment by retsohuang** [comment]
Cool, thanks.

**Comment by bigfish24** [comment]
@retsohuang support added for Realm Swift in version 1.3: https://github.com/bigfish24/ABFRealmMapView/commit/930558abef326833d0c74d472a4d03b69aa35360

**Comment by bigfish24** [comment]
@retsohuang there was a bug in the initial release, v1.4 for Swift is working properly: https://github.com/bigfish24/ABFRealmMapView/commit/0fe2906d989e7d2e2890447c446411de114efa28

**Comment by retsohuang** [comment]
Cool, thanks :+1:
