### ISSUE TITLE
Is Carthage support planned?

### ISSUE THREAD

**Issue by ataibarkai** [bigfish24/ABFRealmMapView#10]

**Comment by bigfish24** [comment]
I hadn't thought about it yet, but will try to add that next week.

**Comment by ataibarkai** [comment]
Great

**Comment by bigfish24** [comment]
This PR is tracking the progress: https://github.com/bigfish24/ABFRealmMapView/pull/13

**Comment by lwalukie** [comment]
Hello, what is the status of carthage support - is it ready? If so, how can I use this library with Carthage?

**Comment by plastic-karma** [comment]
We would also appreciate Carthage support for ABFRealmMapView.

**Comment by bigfish24** [comment]
Sorry I will try to pick up on this next week. Realm is announcing something new next week and I have been heads down all summer. If you want to submit PR to add it would be greatly appreciated.

**Comment by bigfish24** [comment]
Fixed: https://github.com/bigfish24/ABFRealmMapView/commit/4cc389f9d4e5a5545e0071f04547e8f17eeb2dd2
