### ISSUE TITLE
Crash when using latitude and longitude in property

### ISSUE THREAD

**Issue by beseder42** [bigfish24/ABFRealmMapView#16]
My coordinates are stored not stored directly in my Object, but in an property of type Coordinates, which has a latitude and longitude variable of type string. 

`final class Coordinates: Object, Decodable {
    dynamic var longitude: String = ""
    dynamic var latitude: String = ""
}`

I thought it should be possible to access them by using "coordinates.longitude" and "coordinates.latitude" as latitudeKeyPath and longitudeKeyPath.

However the app crashes with this:
`Terminating app due to uncaught exception 'Invalid value', reason: 'Expected object of type string for property 'coordinates.latitude' on object of type 'XXX', but received: 91.17809'`

91.17809 is by the way no available coordinate and even no available value in the Realm. 

Is my approach possible at all? Thanks for any help!

**Comment by bigfish24** [comment]
The latitude and longitude need to be double properties not strings.

**Comment by beseder42** [comment]
Ok, too obvious... thanks a lot! I was using the existing model and was then mislead by the message..
