### ISSUE TITLE
Possible to make it asynchronously?

### ISSUE THREAD

**Issue by frgmt** [bigfish24/ABFRealmMapView#18]
First, thank you very much for sharing this cool realm.io add-on with us.
What I recently recognized is that fetching the data and creating the clustered images on the map is pretty slow and you can't move the map while it is working.
It seems the process of adding things to the map is not dispatched. This makes it a bit unhandy and laggy. Is this right? Or is it just something I got?

**Comment by bigfish24** [comment]
@frgmt thanks for the kind words. I am not sure why this is happening because all of the fetching is occurring on a background queue (via `NSOperation`). Are you doing anything else on the main thread? How have you implemented the map?

**Comment by frgmt** [comment]
@bigfish24 thanks for your fast response. I first just went through your tutorial. So It's not much going on there. [Here](<script src="https://gist.github.com/frgmt/6a61a05732fb89c94966.js"></script>) is a gist where you see my implementation.

**Comment by bigfish24** [comment]
Can you try the example app and verify it has the same issue: https://github.com/bigfish24/ABFRealmMapView/tree/master/ABFRealmMapViewExample
