### ISSUE TITLE
'Realm.Configuration' has no member path

### ISSUE THREAD

**Issue by David2XN** [bigfish24/ABFRealmMapView#19]
## Goals

using RealmMapView

## Actual Results

Pods/RealmMapView/RealmMapView/RealmMapView.swift:282:13: Value of type 'Realm.Configuration' has no member 'path'

## Steps to Reproduce

 - Add following lines to podfile

```
pod 'RealmMapView'
# Map data set
pod 'RealmSwiftSFRestaurantData'
```
 - Build

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.11.5
BuildVersion:	15F34

/Applications/Xcode.app/Contents/Developer
Xcode 7.3.1
Build version 7D1014

/Users/Air/.rvm/gems/ruby-2.1.1/bin/pod
1.0.0
Realm (0.103.1)
RealmSwift (0.103.1)

**Comment by v-ken** [comment]
Any updates on this?

**Comment by v-ken** [comment]
For those looking for a temporary fix, you can use my fork here:

`pod 'RealmMapView', :git => 'https://github.com/v-ken/ABFRealmMapView.git'`

**Comment by khrno** [comment]
Realm configuration has deprecated ```path``` attribute. Use ```fileURL``` instead. Something like this:

```
config.fileURL = [NSURL fileURLWithPath:ABFRestaurantScoresPath()];
```

instead of

```
config.path = ABFRestaurantScoresPath();
```

**Comment by igorcodevog** [comment]
private func toRLMConfiguration(configuration: Realm.Configuration) -> RLMRealmConfiguration {
        let rlmConfiguration = RLMRealmConfiguration()
        
        if (configuration.fileURL != nil) {
            rlmConfiguration.fileURL = configuration.fileURL
        }
        
        if (configuration.inMemoryIdentifier != nil) {
            rlmConfiguration.inMemoryIdentifier = configuration.inMemoryIdentifier
        }
        
        rlmConfiguration.encryptionKey = configuration.encryptionKey
        rlmConfiguration.readOnly = configuration.readOnly
        rlmConfiguration.schemaVersion = configuration.schemaVersion
        return rlmConfiguration
    }

**Comment by chetanpatilv2** [comment]
Try to use this 

Realm.Configuration.defaultConfiguration.fileURL!
