### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ZakShaky** [bigfish24/ABFRealmMapView#2]
Whenever I try to build this Xcode gives me this error:

"Overiding method with selector shouldPerformSegueWithIdentifier has incompatible type"

Thanks

**Comment by bigfish24** [comment]
I can't reproduce this error. When I run the example project it works fine. I would make sure you did `pod install` and opened the `.xcworkspace` file?

**Comment by bigfish24** [comment]
What version of Xcode are you running?
