### ISSUE TITLE
v2.0 not available in CocoaPods

### ISSUE THREAD

**Issue by cybkuz** [bigfish24/ABFRealmMapView#26]
RealmMapView v2.0 not available in cocoapods.
```
[!] Unable to satisfy the following requirements:

- `ABFRealmMapView (>= 2.0)` required by `RealmMapView (2.0)`

None of your spec sources contain a spec satisfying the dependency: `ABFRealmMapView (>= 2.0)`.
```

**Comment by bryan1anderson** [comment]
Same problem, this is pretty vexing

**Comment by bigfish24** [comment]
Fixed now: https://github.com/bigfish24/ABFRealmMapView/commit/26a0998badbf6ff630e13077e64c7077e65c3ab4

Sorry for the delay, a lot of changes to the dependencies caused issues.
