### ISSUE TITLE
No podspec found

### ISSUE THREAD

**Issue by jb80016** [bigfish24/ABFRealmMapView#30]
Anyone else seeing this?

$ pod install
Analyzing dependencies
Fetching podspec for `SwiftFetchedResultsController` from `../../RBQFetchedResultsController`
[!] No podspec found for `SwiftFetchedResultsController` in `../../RBQFetchedResultsController`

**Comment by bigfish24** [comment]
I removed the dependency on `RBQFetchedResultsController`/`SwiftFetchedResultsController`, try updating to v2.1.
