### ISSUE TITLE
Customize cluster annotation image

### ISSUE THREAD

**Issue by ajandrade** [bigfish24/ABFRealmMapView#32]
Hello,

Is it possible to customise the image of the cluster annotations?

Best regards,

**Comment by bigfish24** [comment]
Yes, the included [`ABFClusterAnnotationView.h`](https://github.com/bigfish24/ABFRealmMapView/blob/master/ABFRealmMapView/ABFClusterAnnotationView.h) serves as the default view, but you could subclass it and then override `drawRect:` to customize the image.

You will then need to define `- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id <MKAnnotation>)annotation` as part of `MKMapViewDelegate` and return your custom annotation view. 

If you look into `ABFRealmMapView.m` you will see that all the `MKMapViewDelegate` methods are defined, but they check to see if you set a delegate to override, [see here](https://github.com/bigfish24/ABFRealmMapView/blob/master/ABFRealmMapView/ABFRealmMapView.m#L188).
