### ISSUE TITLE
import error in objective-c version of ABFRealmMapView version 2.0

### ISSUE THREAD

**Issue by Annelies1** [bigfish24/ABFRealmMapView#33]
Hi,

In the installation guide it says "Starting with Xcode 7.1, there is an issue with CocoaPods 0.39 that caused the interop of the Objective-C code for ABFRealmMapView to fail on compile when used in RealmMapView. This problem has now been resolved as of v1.6.6. Please be sure to use this version or higher with Xcode 7.1."

But I still have the same issue in the latest version ABFRealmMapView (2.0) I use now. 
_@import RBQFetchedResultsController;
Build error: Module 'RBQFetchedResultsController' not found in ABFLocationFetchRequest.h_ 

I use the latest cocoapod version 1.2.0
I added this line in my pod file:
pod 'ABFRealmMapView'

with pod install I see the following 
Installing ABFRealmMapView (2.0)
Installing RBQFetchedResultsController (5.0.2)
Installing RBQSafeRealmObject (1.1)
Installing Realm (2.4.4)
Installing RealmUtilities (0.4)

How can I resolve the build error without adjusting the library itself? Because otherwise it will reoccur when updating the library later on. Thanks in advance!

regards,
Annelies

**Comment by bigfish24** [comment]
@Annelies1 I just pushed a fix v2.1, can you try updating your pod to see if this fixes it?

**Comment by Annelies1** [comment]
Thanks @bigfish24  this works!
