### ISSUE TITLE
Cluster's annotation count is not always right

### ISSUE THREAD

**Issue by ajandrade** [bigfish24/ABFRealmMapView#34]
Hi guys.

I was testing the framework and I've found a problem with the count label not being always right.

For example, I have this cluster saying it has one annotation, but if I press it the callout says it has two:
<img width="303" alt="screen shot 2017-03-15 at 23 13 53" src="https://cloud.githubusercontent.com/assets/25066243/23974808/2d3313ce-09d5-11e7-94c0-fe3838cdf14b.png">

And if I zoom in, there are 2 pins there, confirming what is shown in the callout above:
<img width="254" alt="screen shot 2017-03-15 at 23 25 33" src="https://cloud.githubusercontent.com/assets/25066243/23975124/ee8f9a5a-09d6-11e7-9c3e-0e5fc39e7c4f.png">

Maybe a problem when reusing annotations @bigfish24 ? Can you help me on that?

**Comment by bigfish24** [comment]
Can you create a repro case?

**Comment by ajandrade** [comment]
@bigfish24 : Sorry, I was overriding the "viewFor annotation" method and wasn't reseting the counter. My bad. You can close this.

Thanks.

**Comment by bigfish24** [comment]
👍
