### ISSUE TITLE
Setting basePredicate Not Having Any Effect

### ISSUE THREAD

**Issue by jimjeffers** [bigfish24/ABFRealmMapView#37]
Hey there,

I'm setting the base predicate and calling refreshMapView in an attempt to change the filtering used on the map based on some user interaction. The map view annotations disappear but all reappear without any filtering from the base predicate appearing to take place. This also happens if setting the basePredicate on viewDidLoad.

`let allAnnotations = self.mapView.annotations
        self.mapView.removeAnnotations(allAnnotations)
        mapView.basePredicate = NSPredicate(format: "locationType == %@", state.get(string: "locationType"))
        mapView.refreshMapView()`

It appears the condition to unwrap the base predicate along with the fetchRequest predicate never fulfills.

<img width="714" alt="screen shot 2017-04-01 at 10 59 34 pm" src="https://cloud.githubusercontent.com/assets/9150/24584808/0fb29cea-172f-11e7-9efa-b3a29c78a948.png">
<img width="520" alt="screen shot 2017-04-01 at 10 59 52 pm" src="https://cloud.githubusercontent.com/assets/9150/24584809/0fcffd94-172f-11e7-96ee-ee11a69409a1.png">

Any advice? Also on a related note - if I update the basePredicate is the expected behavior that all annotations that don't match the predicate shall be removed from the map automatically or am I correct to assume I'd need to remove annotations from the map before refreshing?

**Comment by jimjeffers** [comment]
Also the break point in the screenshot occurred here:
https://github.com/bigfish24/ABFRealmMapView/blob/d8603a0786a8385f3962b7b7cfa69e3392a6f6af/RealmMapView/RealmMapView.swift#L136

**Comment by bhstrifork** [comment]
You can use my branch until #35 is fixed.

**Comment by bigfish24** [comment]
Sorry this took so long to merge! Thanks for fixing it @bhstrifork
