### ISSUE TITLE
Incorrect calculate clusters on max zoom-out

### ISSUE THREAD

**Issue by spbvasilenko** [bigfish24/ABFRealmMapView#4]
Hey, how I can resolve this issue? Or this is a bug?
https://monosnap.com/file/VsdjbDrBSvSCUHXoDXipFJ6N24i0Kb

**Comment by spbvasilenko** [comment]
This is reproduce on 7 zoom level map view

**Comment by bigfish24** [comment]
I looked at the video, but I am confused on what the issue is? Can you describe the problem you are observing?

**Comment by spbvasilenko** [comment]
When map with max zoom-out level, count of clusters is equal to 758, however I have more points on map. 

I think when the cluster, which displays the number 758, then below it is a few clusters.

**Comment by bigfish24** [comment]
Hmm, yeah I would check the `safeObjects` and `annotations` properties on `ABFLocationFetchedResultsController` to verify.

`safeObjects.count` will be the total number of objects in all clusters. `annotations.count` will give you the number of clusters. Then if you iterate over each `annotation` to check `annotation.safeObjects.count` you will get the number of items in the cluster.

Please verify if this doesn't match.

**Comment by spbvasilenko** [comment]
@bigfish24 I'm check it. Well, if zoom level of map view is equal to 13 and we have maximum zoom-out, I see one cluster on map with count = 732. In debugger console, in delegate viewForAnnotation, I checking count of visible clusters, that's cluster with count 732 and cluster with count 309 safe objects.
Cluster with 309 count non visible on map, because cluster with 732 count is hides it. However, if zoom level of map is equal to 13 and we have non maximum zoom-out, map can display cluster with count 1041 safe objects - this is good. But, with maximum zoom-out map view display incorrect two clusters. It should be one cluster with count 1041 with maximum zoom-out of map.

**Comment by spbvasilenko** [comment]
<img width="835" alt="screen shot 2015-10-09 at 22 25 21" src="https://cloud.githubusercontent.com/assets/7735730/10403511/da9761ca-6ed4-11e5-9cc3-c7d4ca3d1159.png">
<img width="834" alt="screen shot 2015-10-09 at 22 25 42" src="https://cloud.githubusercontent.com/assets/7735730/10403513/dad7ed8a-6ed4-11e5-8016-a582eadbdd09.png">
<img width="834" alt="screen shot 2015-10-09 at 22 26 18" src="https://cloud.githubusercontent.com/assets/7735730/10403512/dad50c28-6ed4-11e5-8beb-c00b320c4ad7.png">

This is screenshots with maximum zoom-out map view and 13 zoom level

**Comment by spbvasilenko** [comment]
This is screenshot with non maximum zoom-out and 13 zoom level of map view and with right work

![simulator screen shot 09 oct 2015 22 26 33](https://cloud.githubusercontent.com/assets/7735730/10403569/4337aa1e-6ed5-11e5-951b-c20134d80c94.png)
<img width="834" alt="screen shot 2015-10-09 at 22 26 18" src="https://cloud.githubusercontent.com/assets/7735730/10403570/47bd93dc-6ed5-11e5-85a9-cfc46b9cdb5f.png">

**Comment by spbvasilenko** [comment]
Second video
https://monosnap.com/file/LazDegyRV2dEqfvSOV3cSLU9SuQDrX

**Comment by bigfish24** [comment]
@spbvasilenko I think this is expected behavior. The reason being is that the clustering is based off of a grid, with each cell of the grid corresponding to a cluster. The resulting annotation view is placed at the center of the average latitude/longitude of all the annotations in the cell.

The zoom level affects the amount of cells in the grid. When you are zoomed in, you want more clusters, so the cell size is smaller than when you are fully zoomed out.

My point with explaining this is that at any zoom level, you can have a situation where the border between two cells in the grid can force the display to appear as two clusters, versus 1 by simply moving the view around and not changing the zoom level.

Does this make sense?

**Comment by bigfish24** [comment]
Here's what I was trying to explain visually:

![fullsizerender](https://cloud.githubusercontent.com/assets/1036685/10405039/4850518a-6e8b-11e5-9f98-c588c1279c20.jpg)

**Comment by spbvasilenko** [comment]
@bigfish24 I understood. But this is incorrect, when tiniest zoom obtained different results like on video, when we have cluster with 732 count and a second cluster invisible under. This is can be fixed or can't? I think this make sense =)

**Comment by bigfish24** [comment]
If you want to play around with the grid size, you can adjust the values returned from the private function:
```objc
static NSUInteger ABFClusterSizeForZoomLevel(ABFZoomLevel zoomLevel)
```
in `ABFLocationFetchedResultsController.m` starting at line 279.

The values it is returning are pixels, so the default value creates a cluster based off of a 88px square cell from the map view. The higher zoom levels have smaller sizes so that the cell is smaller, thus the items are less clustered.

**Comment by bigfish24** [comment]
But note even if you make the cells larger in size, the issue can still occur, because the clustering is grid based, so the dividing line between cells can cut through a large clump of annotations, creating two clusters, which might be so close that the annotation views overlap each other.

**Comment by bigfish24** [comment]
The only way to truly _fix_ this problem is to cluster the annotations through a more complex density clustering mechanism, such as k-means. The downside is that this introduces a lot of extra complexity, so it would slow it down.

**Comment by spbvasilenko** [comment]
@bigfish24 Thank you. I try it ;) As a result , you advise not to change anything?

**Comment by spbvasilenko** [comment]
@bigfish24 Well, playing with ABFClusterSizeForZoomLevel helps me. If setting 86 size for 13 zoom level it fine works for me. 
As second option fix this, I think may be disable maximum zoom-out for Map View

**Comment by bigfish24** [comment]
I think it might be best to make public a way to customize the grid size, since each use case can be different, as you are experiencing. Let me think a bit about what's the best approach. I think a delegate where you can return the size based on the zoom level makes the most sense.

**Comment by spbvasilenko** [comment]
Okey. I will wait.

**Comment by bigfish24** [comment]
Ok, v1.5 has the feature you need: https://github.com/bigfish24/ABFRealmMapView/commit/c1ebfa9ea2c0224d9940469e7c6f4c1f24a3ff13

you can simply override `clusterSizeBlock` on `ABFLocationFetchedResultsController`. The default block looks like this:

```objc
ABFClusterSizeForZoomLevel ABFDefaultClusterSizeForZoomLevel()
{
    return ^NSUInteger(ABFZoomLevel zoomLevel) {
        switch (zoomLevel) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 13:
            case 14:
            case 15:
                return 64;
            case 16:
            case 17:
            case 18:
                return 32;
            case 19:
                return 16;
            case 20:
            default:
                return 88;
        }
    };
}
```

**Comment by spbvasilenko** [comment]
@bigfish24, ok, great! Thank you!
