### ISSUE TITLE
Add a tutorial to get items

### ISSUE THREAD

**Issue by ppamorim** [bigfish24/ABFRealmMapView#7]
Hi Adam!
What do you think about to add a tutorial to get the itens inside de clustered item? I need do it on my application, but I don`t know how to do it :(

**Comment by spbvasilenko** [comment]
@ppamorim Hey, you can items inside cluster on delegate methods map view like this: didSelectAnnotation, after that, you can take ABFClusterAnnotation and inside annotation will be array with SafeRealmObjects

**Comment by bigfish24** [comment]
@ppamorim pI I added some helper methods to make it easier to get your objects. Check out this release: https://github.com/bigfish24/ABFRealmMapView/commit/55ade6675c5fec370ebc6156709227bc9e486749

The example apps for Swift and Objective-C demonstrate how you can use the class method `safeObjectsForClusterAnnotationView:` on `ABFClusterAnnotationView` to retrieve the safe objects in the cluster from the annotation return in the `MKMapViewDelegate` `mapView:didSelectAnnotationView`:

**Objective-C**
```objc
- (void)mapView:(MKMapView *)mapView didSelectAnnotationView:(MKAnnotationView *)view
{
    NSArray<ABFLocationSafeRealmObject *> *safeObjects = [ABFClusterAnnotationView safeObjectsForClusterAnnotationView:view];
    
    ABFRestaurantObject *firstObject = safeObjects.firstObject.RLMObject;
    
    NSLog(@"First Object: %@",firstObject.name);
    NSLog(@"Cluster Count: %lu",safeObjects.count);
}
```
**Swift**
```swift
func mapView(mapView: MKMapView, didSelectAnnotationView view: MKAnnotationView) {
        if let safeObjects = ABFClusterAnnotationView.safeObjectsForClusterAnnotationView(view) {
            
            if let firstObject = safeObjects.first?.toObject(ABFRestaurantObject) {
                print("First Object: \(firstObject.name)")
            }
            
            print("Count: \(safeObjects.count)")
        }
    }
```

**Comment by ppamorim** [comment]
@bigfish24 I noticed that RealmMapView-Swift, at line 92, needs to change this line to work:

For this:
```objc
#import <RealmMapView/RealmMapView.h>
```
To this:
```objc
#import <RealmMapView/RealmMapView-Swift.h>
```
