### ISSUE TITLE
Crash when interrupt internet connection

### ISSUE THREAD

**Issue by ppamorim** [bigfish24/ABFRealmMapView#9]
Hi Realm team.
While I`m testing my app, I noticed that RealmMapView(1.4.1) has a problem to handle the interruption of internet connection. The app crashes because an error (@RealmMapView.swift, line 270) of the loading map happen. (The problem happen with my sample app too, Fun-With-Swift).

![captura de tela 2015-12-02 as 09 45 38](https://cloud.githubusercontent.com/assets/5521682/11530323/c54ff982-98da-11e5-93c2-047fd8ce91d2.png)

Test it if you can. Start the app, wait the map to load and disable your internet connection, drag the map and bang! This problem happen with the emulator. But I don't think it is a problem with the emulator/device.

Swift 2
Xcode 7.0.1
CocoaPod 0.39.0

**Comment by bigfish24** [comment]
Thanks for filing this, I will see if I can figure out what's going.
